WebMVC/Areas/Admin/Controllers/BranchesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;
using WebMVC.Repository.IRepository;

namespace WebMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BranchesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BranchesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _unitOfWork.Branch.GetAllAsync(SD.BranchPath, Request.Cookies["JWToken"]) });
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            Branch obj = new();

            if (id == null || id == 0)
            {
                //this will be true for Insert/Create
                return View(obj);
            }

            //Flow will come here for update
            obj = await _unitOfWork.Branch.GetFirstOrDefaultAsync(SD.BranchPath, id.GetValueOrDefault(), Request.Cookies["JWToken"]);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Branch obj)
        {
            if (!ModelState.IsValid) return View(obj);

            if (obj.Id == 0)
            {
                // Create
                await _unitOfWork.Branch.AddAsync(SD.BranchPath, obj, Request.Cookies["JWToken"]);
                TempData["success"] = "Branch created successfully";
            }
            else
            {
                // update
                await _unitOfWork.Branch.UpdateAsync(SD.BranchPath + obj.Id, obj, Request.Cookies["JWToken"]);
                TempData["success"] = "Branch updated successfully";
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _unitOfWork.Branch.RemoveAsync(SD.BranchPath, id, Request.Cookies["JWToken"]);
            if (status)
            {
                return Json(new { success = true, message = "Delete Successful" });
            }
            return Json(new { success = false, message = "Delete Not Successful" });
        }
    }
}

WebMVC/Areas/Admin/Controllers/ReservationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IdentityModel.Tokens.Jwt;
using WebMVC.Models;
using WebMVC.Repository.IRepository;
using WebMVC.ViewModels;

namespace WebMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ReservationsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ReservationsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _unitOfWork.Reservation.GetAllAsync(SD.ReservavtionPath, Request.Cookies["JWToken"]) });
        }
        public async Task<IActionResult> GetAllByUserId()
        {
            var jwtSecurityToken = new JwtSecurityTokenHandler().ReadJwtToken(Request.Cookies["JWToken"]);
            var uid = jwtSecurityToken.Claims.First(claim => claim.Type == "uid").Value;
            return View(await _unitOfWork.Reservation.GetAllAsync(SD.ReservavtionPath + "GetByUserId/" + uid, Request.Cookies["JWToken"]));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Upsert(int? id)
        {
            var handler = new JwtSecurityTokenHandler();
            var jwtSecurityToken = handler.ReadJwtToken(Request.Cookies["JWToken"]);
            var uid = jwtSecurityToken.Claims.First(claim => claim.Type == "uid").Value;
            IEnumerable<Room> roomList = await _unitOfWork.Room.GetAllAsync(SD.RoomPath, Request.Cookies["JWToken"]);
            ReservationVM obj = new()
            {
                Reservation = new Reservation() { ApplicationUserId = uid },

                RoomList = roomList.Select(i => new SelectListItem
                {
                    Text = i.RoomNumber.ToString(),
                    Value = i.Id.ToString()
                }),
            };

            if (id == null || id == 0)
            {
                //this will be true for Insert/Create
                return View(obj);
            }

            //Flow will come here for update
            obj.Reservation = await _unitOfWork.Reservation.GetFirstOrDefaultAsync(SD.ReservavtionPath, id.GetValueOrDefault(), Request.Cookies["JWToken"]);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Upsert(ReservationVM obj)
        {

            if (!ModelState.IsValid) return View(obj);

            if (obj.Reservation.Id == 0)
            {
                // Create

                await _unitOfWork.Reservation.AddAsync(SD.ReservavtionPath, obj.Reservation, Request.Cookies["JWToken"]);
                TempData["success"] = "Branch created successfully";
            }
            else
            {
                // update
                await _unitOfWork.Reservation.UpdateAsync(SD.ReservavtionPath + obj.Reservation.Id, obj.Reservation, Request.Cookies["JWToken"]);
                TempData["success"] = "Branch updated successfully";
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _unitOfWork.Reservation.RemoveAsync(SD.ReservavtionPath, id, Request.Cookies["JWToken"]);
            if (status)
            {
                return Json(new { success = true, message = "Delete Successful" });
            }
            return Json(new { success = false, message = "Delete Not Successful" });
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create(int roomId)
        {
            var jwtSecurityToken = new JwtSecurityTokenHandler().ReadJwtToken(Request.Cookies["JWToken"]);
            var uid = jwtSecurityToken.Claims.First(claim => claim.Type == "uid").Value;

            var room = await _unitOfWork.Room.GetFirstOrDefaultAsync(SD.RoomPath, roomId, Request.Cookies["JWToken"]);

            return View(new Reservation()
            {
                RoomId = roomId,
                ApplicationUserId = uid,
                Room = room,
            });
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Reservation obj)
        {
            if (!ModelState.IsValid) return View(obj);

            await _unitOfWork.Reservation.AddAsync(SD.ReservavtionPath, obj, Request.Cookies["JWToken"]);

            TempData["success"] = "Branch created successfully";

            return RedirectToAction(nameof(GetAllByUserId));
        }

    }
}

WebMVC/Areas/Admin/Controllers/RoomTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;
using WebMVC.Repository.IRepository;

namespace WebMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoomTypesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RoomTypesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _unitOfWork.RoomType.GetAllAsync(SD.RoomTypePath, Request.Cookies["JWToken"]) });
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            RoomType obj = new();

            if (id == null || id == 0)
            {
                //this will be true for Insert/Create
                return View(obj);
            }

            //Flow will come here for update
            obj = await _unitOfWork.RoomType.GetFirstOrDefaultAsync(SD.RoomTypePath, id.GetValueOrDefault(), Request.Cookies["JWToken"]);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(RoomType obj)
        {
            if (!ModelState.IsValid) return View(obj);

            if (obj.Id == 0)
            {
                // Create
                await _unitOfWork.RoomType.AddAsync(SD.RoomTypePath, obj, Request.Cookies["JWToken"]);
                TempData["success"] = "RoomType created successfully";
            }
            else
            {
                // update
                await _unitOfWork.RoomType.UpdateAsync(SD.RoomTypePath + obj.Id, obj, Request.Cookies["JWToken"]);
                TempData["success"] = "RoomType updated successfully";
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _unitOfWork.RoomType.RemoveAsync(SD.RoomTypePath, id,Request.Cookies["JWToken"]);
            if (status)
            {
                return Json(new { success = true, message = "Delete Successful" });
            }
            return Json(new { success = false, message = "Delete Not Successful" });
        }
    }
}

WebMVC/Areas/Admin/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebMVC.Models;
using WebMVC.Repository.IRepository;
using WebMVC.ViewModels;

namespace WebMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class RoomsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RoomsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _unitOfWork.Room.GetAllAsync(SD.RoomPath, Request.Cookies["JWToken"]) });
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            IEnumerable<Branch> branchList = await _unitOfWork.Branch.GetAllAsync(SD.BranchPath, Request.Cookies["JWToken"]);
            IEnumerable<RoomType> roomTypeList = await _unitOfWork.RoomType.GetAllAsync(SD.RoomTypePath, Request.Cookies["JWToken"]);
            RoomVM obj = new()
            {
                Room = new Room(),
                BranchList = branchList.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                RoomTypeList = roomTypeList.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),

            };

            if (id == null || id == 0)
            {
                //this will be true for Insert/Create
                return View(obj);
            }

            //Flow will come here for update
            obj.Room = await _unitOfWork.Room.GetFirstOrDefaultAsync(SD.RoomPath, id.GetValueOrDefault(), Request.Cookies["JWToken"]);
            if (obj.Room == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(RoomVM obj)
        {
            if (!ModelState.IsValid) return View(obj);

            if (obj.Room.Id == 0)
            {
                // Create
                await _unitOfWork.Room.AddAsync(SD.RoomPath, obj.Room, Request.Cookies["JWToken"]);
                TempData["success"] = "Room created successfully";
            }
            else
            {
                // update
                await _unitOfWork.Room.UpdateAsync(SD.RoomPath + obj.Room.Id, obj.Room, Request.Cookies["JWToken"]);
                TempData["success"] = "Room updated successfully";
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _unitOfWork.Room.RemoveAsync(SD.RoomPath, id, Request.Cookies["JWToken"]);
            if (status)
            {
                return Json(new { success = true, message = "Delete Successful" });
            }
            return Json(new { success = false, message = "Delete Not Successful" });
        }
        public async Task<IActionResult> RepostPage()
        {
            return View(await _unitOfWork.Room.ReportLike(SD.RoomPath , Request.Cookies["JWToken"]));
        }
    }
}

WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMVC</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Bootstarp Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- Toaster css CDN -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <!-- DataTables css CDN -->
    @*<link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />*@
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.min.css" />
    <!-- Main Styles -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Client" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Client" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Client" asp-controller="Home" asp-action="SearchRoom">Search Room</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Reservations" asp-action="GetAllByUserId">Reservations</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managment
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="Branches" asp-action="Index">Branches</a>
                                    <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="RoomTypes" asp-action="Index">RoomType</a>
                                    <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="Rooms" asp-action="Index">Rooms</a>
                                    <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="Reservations" asp-action="Index">Reservations</a>

                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item nav-link text-dark" asp-area="Admin" asp-controller="Rooms" asp-action="RepostPage">Report</a>

                                </div>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstarp CDN Bundle JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- sweetalert2 CDN -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- DataTables js CDN -->
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <!-- toastr js CDN -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebMVC/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success("@TempData["success"]");
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error("@TempData["success"]");
    </script>
}